image: "docker:latest"

services:
- docker:dind

before_script:
- docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  script:
  - docker build -t "writefreely" .
  - docker tag "writefreely" "$CI_REGISTRY/$CI_PROJECT_PATH/writefreely:0.12.0"
  - docker tag "writefreely" "$CI_REGISTRY/$CI_PROJECT_PATH/writefreely:latest"
  - docker push "$CI_REGISTRY/$CI_PROJECT_PATH/writefreely:0.12.0"
  - docker push "$CI_REGISTRY/$CI_PROJECT_PATH/writefreely:latest"
